### ISSUE TITLE
Eliminate All Support-Logging Tests That Deal With Labels

### ISSUE THREAD

**Issue by tsconn23** [edgexfoundry/blackbox-testing#112]
See issue https://github.com/edgexfoundry/edgex-go/issues/904

We need to remove all blackbox tests that verify support-logging endpoints dealing with labels since the API endpoints will be eliminated. These would be GET/DELETEs. Tests can be removed at any time. I'm not sure when the above issue will be assigned/completed, but it will be during the Edinburgh cycle.

**Comment by weichou1229** [comment]
@cloudxxx8 I already remove these APIs at PR https://github.com/edgexfoundry/blackbox-testing/pull/116

**Comment by tsconn23** [comment]
I'm re-opening this issue due to label-related test/schema data that is still present.

Examples include
[Labels in POST body #1](https://github.com/edgexfoundry/blackbox-testing/blob/63731a03ed4f93d8b6f8afeaf82fcd0c6dfdf14d/bin/postman-test/collections/support-logging.postman_collection.json#L48)

[Labels in POST body #2](https://github.com/edgexfoundry/blackbox-testing/blob/63731a03ed4f93d8b6f8afeaf82fcd0c6dfdf14d/bin/postman-test/collections/support-logging.postman_collection.json#L1292)

[Log entry schema](https://github.com/edgexfoundry/blackbox-testing/blob/63731a03ed4f93d8b6f8afeaf82fcd0c6dfdf14d/bin/postman-test/collections/support-logging.postman_collection.json#L1411)

**Comment by weichou1229** [comment]
@tsconn23 Thanks for your review, I have created a PR https://github.com/edgexfoundry/blackbox-testing/pull/126 to fix this issue.
