### ISSUE TITLE
core-metadata/deviceservice test 224 failure

### ISSUE THREAD

**Issue by tsconn23** [edgexfoundry/blackbox-testing#127]
The following test is failing due to the URL below being sent to the metadata service

- 224 GET http://localhost:48081/api/v1/deviceservice/{{getDeviceServiceById}}

The key shown in the URL above is not present in the data json file and appears to be populated via javascript. The `{{getDeviceServiceById}}` value relies on a previous test 210 which has an error. I can duplicate the issue by doing the following:

1.) Clean Mongo
2.) Run the core-metadata-importer collection
3.) Under "Collections" on the left, expand the deviceservice folder and double click test 210
4.) In the right hand panel, change the URL to the following: `{{baseUrl}}/api/v1/deviceservice/name/Common room thermostat deviceservice`
5.) Hit the "Send" button
6.) At the bottom, "Test Results" will have the following error
`There was an error in evaluating the test script:  TypeError: Cannot read property '$ref' of undefined`

In the console output, I see a successful response with the device service properties followed by the `TypeError` message. I would try to address this myself, but I'm unsure what the approach should be.

**Comment by weichou1229** [comment]
@tsconn23 
The error is due to data.ObjectSchema is undefined.
```
tests["Is Valid Response Schema"] = tv4.validate(deviceService, data.ObjectSchema);
```

If we want to test by Postman GUI tool, we need to define JSON schema and make changes in the test script.
I created a PR https://github.com/edgexfoundry/blackbox-testing/pull/130 to demo this approach.
```
var schemas = {} ; 
schemas.DeviceService = {
   ...
}

var schema = pm.globals.get("schemas").DeviceService;
...
tests["Is Valid Response Schema"] = tv4.validate(deviceService, schema);
```

**Comment by tsconn23** [comment]
Thanks for the assist @weichou1229
