### ISSUE TITLE
Need to add Scheduler Service Black Box testing scripts and tests

### ISSUE THREAD

**Issue by xmlviking** [edgexfoundry/blackbox-testing#134]
With the rewrite of the scheduler service black box tests will need to be created.
A new set of scripts and tests will need to be created for Scheduler Service.

Summary:  Scheduler Service was heavily dependent on the Core-Metadata service as well as it's associated database.   The new version of the scheduler does not use anything from the core-metadata service nor it's database.   All of the existing core-metadata service calls and functionality with schedule and schedule events still exists and will still work.   This new work is in an effort to separate concerns between device services needs for scheduling and all others internal to the edgex platform.  example data clean up etc. 

This includes but is not limited too:
- Data Scripts
- Test Scripts
- Flush Scripts

The first pass of the Black Box tests for Scheduler will be a migration of some of the existing core-metadata tests.   With this move we will have at least the bare minimum of existing functionality which is to be expected of the migration effort. 

Issue: #16 
Addresses part of this Issue as well.

**Comment by xmlviking** [comment]
Closed issue #141 as it was related to this issue
status - waiting on feedback and our guidance in the black box area meeting scheduled

**Comment by cloudxxx8** [comment]
fixed by #153
