### ISSUE TITLE
Blackbox tests for remaining micro services

### ISSUE THREAD

**Issue by jpwhitemn** [edgexfoundry/blackbox-testing#16]
Support (logging, notifications, scheduling, rules engine)
Export Client
Possibly device services and/or DS SDK

**Comment by JPWKU** [comment]
@jpwhitemn what about testing the lastest core go services.  Is that a good first step?

**Comment by jpwhitemn** [comment]
Jeremy,I assume you mean automated kick off and email reporting of blackbox core go services?  If so, yes - good first step.  +1
    On Friday, May 11, 2018, 3:06:53 PM CDT, Jeremy Phelps <notifications@github.com> wrote:  
 
 
@jpwhitemn what about testing the lastest core go services. Is that a good first step?

**Comment by jpwhitemn** [comment]
Completed in California for core, supporting and export services.  To be worked as part of device service SDK.
