### ISSUE TITLE
Postman/newman image ubuntu1404 has been deprecated. 

### ISSUE THREAD

**Issue by tingyuz** [edgexfoundry/blackbox-testing#166]
The current postman/newman docker image we are using (ubuntu1404:3.10.0) has some issues related to ssl/tls suites that too old to be supported by most servers ( mainly SSLv2/SSLV3 are excluded from mainstream servers due to poodle vulnerability).  As a result some of the security blackbox testing cases are failed at ssl handshake stage.

The recommendation from postman/newman is to use postman/newman:ubuntu instead. https://github.com/postmanlabs/newman/tree/master/docker/images/ubuntu1404

**Comment by cloudxxx8** [comment]
@tingyuz will you have time to fix this issue?

**Comment by tingyuz** [comment]
I am using new newman image already in the security testing. In the env.sh I have coded like this:

if [ "$SECURITY_SERVICE_NEEDED" = "true" ]; then
  export postman=postman/newman
else
  export postman=postman/newman_ubuntu1404:3.10.0
fi 

I can open a PR and update the code to use postman/newman for all testing if it looks good.

**Comment by cloudxxx8** [comment]
@tingyuz We might not need to the if determination, because we could apply the new newman image to all the test.
However, we had better add a version tag with a stable to prevent any unexpected change from the latest newman.

**Comment by tingyuz** [comment]
Addressed in #180.
