### ISSUE TITLE
Metadata/ProvisionWatcher Import: OperatingState Is Empty

### ISSUE THREAD

**Issue by tsconn23** [edgexfoundry/blackbox-testing#174]
During the ProvisionWatcher step of metadata-import, OperatingState is not specified and is therefore empty. It should either be `ENABLED` or `DISABLED`. Sample JSON definition from `core-metadata-importer.postman_collection.json`

```
"  \"_class\": \"org.edgexfoundry.domain.meta.ProvisionWatcher\",",
"  \"name\": \"lonmark watcher\",",
"  \"identifiers\": {",
"    \"MAC\": \"00-05-1C-C1-99-99\",",
"    \"HTTP\": \"10.0.0.4\"",
"  },",
"  \"origin\": 1471806386919,",
"  \"profile\": {",
"    \"name\": \"variable speed motor profile\"",
"  },",
"  \"service\": {",
"    \"name\": \"home variable speed motor device service\"",
"  }",
```
As you can see, no `OperatingState` field. Interestingly I found this because an error is correctly thrown when running core-metadata with Redis database. No error is thrown when using Mongo, which means there's a bug somewhere in metadata as well.

**Comment by cloudxxx8** [comment]
@cherrycl please help take care of this issue. thanks.

**Comment by tsconn23** [comment]
@cherrycl I have a question -- How is the `_class` field used? That looks to me like it's specifying a Java class definition. Is that field actually being used anywhere? If so, are we validating schema based on a legacy definition.

FWIW, current ProvisionWatcher definition is here
https://github.com/edgexfoundry/go-mod-core-contracts/blob/master/models/provisionwatcher.go

**Comment by tsconn23** [comment]
Related edgex-go bug created
https://github.com/edgexfoundry/edgex-go/issues/1145

**Comment by cloudxxx8** [comment]
@tsconn23 `_class` is the legacy script, and I've confirmed it is useless now.  The original test data was copied from MongoDB output and the data was stored by old Java services at that time.  The Java OR mapping library generates this additional field in MongoDB to indicate which Java class should be used to deserialize the record.  I will open another issue to clean up this field from the script.
