### ISSUE TITLE
Modify Device Report test to fit Schedule Event removal

### ISSUE THREAD

**Issue by cloudxxx8** [edgexfoundry/blackbox-testing#178]
Since Schedule and Schedule Event are removed from data model according to https://github.com/edgexfoundry/go-mod-core-contracts/pull/28, Device Report will associate to Interval Action instead of Schedule Event.
The related test script should be updated accordingly.

**Comment by cloudxxx8** [comment]
@cherrycl please look into this issue
thanks

**Comment by tsconn23** [comment]
Be advised that the DeviceReport is probably also going to be removed. If this isn't causing an actual error in the test run, I wouldn't spend any cycles on it.

**Comment by cherrycl** [comment]
I will fix this issue after edgex-go/go.mod is updated to latest.

**Comment by cloudxxx8** [comment]
@tsconn23 edgexfoundry/go-mod-core-contracts#28 will cause some error about DeviceReport, so we need to fix.  The test data of DeviceReport contains ScheduleEvent

**Comment by tsconn23** [comment]
> I will fix this issue after edgex-go/go.mod is updated to latest.

@cherrycl PR was merged
