### ISSUE TITLE
Add time out mechanism for black box test

### ISSUE THREAD

**Issue by cloudxxx8** [edgexfoundry/blackbox-testing#184]
We got the stuck more one days several times, and we should make it time out instead of running forever

https://jenkins.edgexfoundry.org/view/blackbox-testing/job/blackbox-testing-security-ubuntu18.04-docker-arm64-4c-2g-master/38/consoleFull
> 00:19:38 An HTTP request took too long to complete. Retry with --verbose to obtain debug information.
> 00:19:38 If you encounter this issue regularly because of slow network conditions, consider setting COMPOSE_HTTP_TIMEOUT to a higher value (current value: 60).
> 00:19:38 Info: Metadata Test completed.
> 00:19:38 Info: Clean CoreMetadata's test data.
> 00:19:38 ./run.sh: line 115:  8109 Terminated              testAll
> 00:19:38       8110                       | tee $EDGEXLOGSPATH
> 00:21:44 An HTTP request took too long to complete. Retry with --verbose to obtain debug information.
> 00:21:44 If you encounter this issue regularly because of slow network conditions, consider setting COMPOSE_HTTP_TIMEOUT to a higher value (current value: 60).
> 00:24:37 ERROR: Step ‘Allure Report’ aborted due to exception: 
> 00:24:37 java.lang.InterruptedException
> 00:24:37 	at java.lang.Object.wait(Native Method)
> 00:24:37 	at hudson.remoting.Request.call(Request.java:177)
> 00:24:37 	at hudson.remoting.Channel.call(Channel.java:954)
> 00:24:37 	at hudson.FilePath.act(FilePath.java:1072)
> 00:24:37 	at hudson.FilePath.act(FilePath.java:1061)
> 00:24:37 	at hudson.FilePath.installIfNecessaryFrom(FilePath.java:915)
> 00:24:37 	at hudson.FilePath.installIfNecessaryFrom(FilePath.java:848)
> 00:24:37 	at hudson.tools.DownloadFromUrlInstaller.performInstallation(DownloadFromUrlInstaller.java:77)
> 00:24:37 	at hudson.tools.InstallerTranslator.getToolHome(InstallerTranslator.java:72)
> 00:24:37 	at hudson.tools.ToolLocationNodeProperty.getToolHome(ToolLocationNodeProperty.java:109)
> 00:24:37 	at hudson.tools.ToolInstallation.translateFor(ToolInstallation.java:206)
> 00:24:37 	at ru.yandex.qatools.allure.jenkins.tools.AllureCommandlineInstallation.forNode(AllureCommandlineInstallation.java:108)
> 00:24:37 	at ru.yandex.qatools.allure.jenkins.tools.AllureCommandlineInstallation.forNode(AllureCommandlineInstallation.java:33)
> 00:24:37 	at ru.yandex.qatools.allure.jenkins.utils.BuildUtils.setUpTool(BuildUtils.java:39)
> 00:24:37 	at ru.yandex.qatools.allure.jenkins.AllureReportPublisher.getCommandline(AllureReportPublisher.java:335)
> 00:24:37 	at ru.yandex.qatools.allure.jenkins.AllureReportPublisher.generateReport(AllureReportPublisher.java:290)
> 00:24:37 	at ru.yandex.qatools.allure.jenkins.AllureReportPublisher.perform(AllureReportPublisher.java:218)
> 00:24:37 	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:81)
> 00:24:37 	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
> 00:24:37 	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:744)
> 00:24:37 	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:690)
> 00:24:37 	at hudson.model.Build$BuildExecution.post2(Build.java:186)
> 00:24:37 	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:635)
> 00:24:37 	at hudson.model.Run.execute(Run.java:1835)
> 00:24:37 	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
> 00:24:37 	at hudson.model.ResourceController.execute(ResourceController.java:97)
> 00:24:37 	at hudson.model.Executor.run(Executor.java:429)
> 00:24:37 [BFA] Scanning build for known causes...
> 00:24:37 [BFA] No failure causes found
> 00:24:37 [BFA] Done. 0s
> 00:24:38 Finished: FAILURE

**Comment by weichou1229** [comment]
Build process block at `23:37:27` API request and aborted at `00:18:25`. 
In this situation,  Jenkins master didn't get any response from slave anymore, just like disconnection or slave is busy to response.
It's might be too many jobs queue on the slave or some performance isseue.
```
23:18:00 Started by GitHub push by JPWKU
...
23:37:27 ↳ 308 http://localhost:48081/api/v1/provisionwatcher
23:37:27   PUT http://edgex-core-metadata:48081/api/v1/provisionwatcher Build timed out (after 60 minutes). Marking the build as failed.
00:18:25 $ ssh-agent -k
00:18:25 unset SSH_AUTH_SOCK;
00:18:25 unset SSH_AGENT_PID;
00:18:25 echo Agent pid 2108 killed;
00:18:25 [ssh-agent] Stopped.
00:18:25 Build was aborted
...
00:24:38 Finished: FAILURE
```

**Comment by weichou1229** [comment]
In recent build job, they both fail at here, but I don't have any clue about this.
```
10:47:54 Pulling kong-migration (kong:0.13.0)...
10:47:55 no matching manifest for unknown in the manifest list entries
10:47:55 Build step 'Execute shell' marked build as failure
```
https://jenkins.edgexfoundry.org/view/blackbox-testing/job/blackbox-testing-security-ubuntu18.04-docker-arm64-4c-2g-master/39/console
https://jenkins.edgexfoundry.org/view/blackbox-testing/job/blackbox-testing-security-ubuntu18.04-docker-arm64-4c-2g-master/40/console

**Comment by weichou1229** [comment]
https://github.com/Kong/docker-kong/issues/39
It seems didn't support official image for arm64

**Comment by cloudxxx8** [comment]
add @tingyuz for awareness of this issue

**Comment by cloudxxx8** [comment]
close this issue since the original topic is due to the issue of Jenkins node
