### ISSUE TITLE
Support-Notification: No response data returned when endDate set to "1600000" on /end/{{endDate}}/{{limit}} api

### ISSUE THREAD

**Issue by cherrycl** [edgexfoundry/blackbox-testing#186]
The "endDate" format should change to correct timestamp.

Blackbox test result

> 12:42:51 ↳ Query notifications by creation timestamp before end date with limited returned records
> 12:42:51   GET http://edgex-support-notifications:48060/api/v1/notification/end/1600000/2 [200 OK, 417B, 16ms]
> 12:42:51   ✓  Status code is 200
> 12:42:51   ✓  Response time is less than 800ms
> 12:42:51   ✓  Content-Type is present
> 12:42:51   ✓  Content-Type is application/json
> 12:42:51   2. Response body is correct
> 12:42:51   ✓  Is valid response schema

**Comment by akramtexas** [comment]
- My understanding is that (the fix to) this issue is _independent_ of the following issue: [Create a critical notification takes time over 1s #1187](https://github.com/edgexfoundry/edgex-go/issues/1187)
