### ISSUE TITLE
Remove "Readings by Device and Value Descriptor up to X Results" test

### ISSUE THREAD

**Issue by tsconn23** [edgexfoundry/blackbox-testing#187]
The following test in the core-data/event suite should be removed:
27 - http://localhost:48080/api/v1/event/device/:deviceId/valuedescriptor/{valuedescriptor}/{limit} 

There is a pending PR for the removal of this endpoint https://github.com/edgexfoundry/edgex-go/pull/1209

For additional context as to why this is being removed, please see this issue:
https://github.com/edgexfoundry/edgex-go/issues/1194

Also, the core-data Client function that would allow this endpoint to be called is not part of the [ReadingClient](https://github.com/edgexfoundry/go-mod-core-contracts/blob/ed80a34a1c6e6b174ed14ce3e992c0eb507f9050/clients/coredata/reading.go#L30) interface currently, so it's uncallable except via a direct REST invocation like Postman. See the following issue https://github.com/edgexfoundry/go-mod-core-contracts/issues/45

**Comment by cloudxxx8** [comment]
fixed by #188
