### ISSUE TITLE
Interlock -- Rename DeviceProfile Properties

### ISSUE THREAD

**Issue by tsconn23** [edgexfoundry/blackbox-testing#197]
See edgexfoundry/go-mod-core-contracts#59 for context.

Integration with edgex-go is being tracked here https://github.com/edgexfoundry/edgex-go/issues/1231

In anticipation of a PR for the edgex-go changes, tests that refer to the affected properties need to change the names as appropriate.

**Comment by cloudxxx8** [comment]
fixed by #198
