### ISSUE TITLE
Sample Events in Mongo Don't Have Age Specified

### ISSUE THREAD

**Issue by tsconn23** [edgexfoundry/blackbox-testing#20]
There's a test that fails in the core-data collection which calls the following URL as an HTTP DELETE

localhost:48080/api/v1/event/removeold/age/1000000000000

It fails because the controller returns 0 since no events were deleted. No events were deleted because in the DataDumps/coredata/eventDB.json, none of the events have a specified age.

**Comment by cloudxxx8** [comment]
May I know it is failed on go or java version?
There is no specified age like this, because the age is always changing.
However, this API should delete all the data which is older than the parameter.

**Comment by cloudxxx8** [comment]
The final record in the eventDB.json contains "created": 474848468956, so it should be always qualified for this test.

**Comment by cloudxxx8** [comment]
Could you please check the date time settings of the test machine is correct?

**Comment by tsconn23** [comment]
Ah, OK. I see what you're saying. I'll be going through more of the blackbox testing tomorrow and will review this again. If it turns out to be my bad, I'll close the issue.
