### ISSUE TITLE
Need Tests for Core-Command Name-based endpoints

### ISSUE THREAD

**Issue by tsconn23** [edgexfoundry/blackbox-testing#203]
Please see the following issue for context https://github.com/edgexfoundry/edgex-go/issues/1223

We'll need tests to support these new endpoints whereby commands can be fetched by their name, as well as a list of commands for a given device by the device name.

@difince @cloudxxx8 for visibility

**Comment by cloudxxx8** [comment]
@FelixTing please help take care of this one when you have time
