### ISSUE TITLE
Need Blackbox Tests for the SMA.

### ISSUE THREAD

**Issue by akramtexas** [edgexfoundry/blackbox-testing#204]
- We want to have a set of ready-to-run Blackbox Tests to catch regression bugs for the SMA.

**Comment by akramtexas** [comment]
- Work is currently underway on a [feature branch of my fork of the blackbox-testing repo](https://github.com/akramtexas/blackbox-testing/tree/create_sma__tests)

**Comment by cloudxxx8** [comment]
this issue will be closed after the test added to script
@weichou1229 please use this issue to open another PR, so we don't have to open a new issue for this

**Comment by weichou1229** [comment]
No problem, I will add shell script for executing the postman script when the image is ready.
https://nexus3.edgexfoundry.org/#browse/browse:docker.staging

**Comment by cloudxxx8** [comment]
@akramtexas please notify us when the SMA image is ready to test

**Comment by michaelestrin** [comment]
Closing.  Superseded by https://github.com/edgexfoundry/blackbox-testing/issues/272
