### ISSUE TITLE
Interlock -- Model Validation Requires Request Integrity

### ISSUE THREAD

**Issue by tsconn23** [edgexfoundry/blackbox-testing#205]
Team -- I have a PR outstanding that encapsulates HTTP request validation within the request models found in `go-mod-core-contracts`

https://github.com/edgexfoundry/go-mod-core-contracts/pull/71

This is the result of quite a bit of discussion in the Core Working Group, the point of which was that we identified that in many cases it was possible to submit a request to our REST APIs that was not valid. The following issue is the one that started this effort

https://github.com/edgexfoundry/blackbox-testing/issues/174

The PR for `go-mod-core-contracts` is complete and I am working on a follow up PR to integrate it into `edgex-go`. As part of my due diligence, I want to run the blackbox tests against the upcoming edgex-go PR. However I have found that we have a lot of issues in our blackbox test scripts with request integrity. Fields that are supposed to have a required value are not populated. Here is an example of the errors thrown by core-metadata when running the `core-metadata-importer` collection via Postman.

```
level=ERROR ts=2019-04-24T16:09:59.889698Z app=edgex-core-metadata source=rest_deviceprofile.go:52 msg="Name cannot be blank"
level=ERROR ts=2019-04-24T16:10:00.453664Z app=edgex-core-metadata source=rest_device.go:61 msg="invalid OperatingState \"\""
level=ERROR ts=2019-04-24T16:10:00.453818Z app=edgex-core-metadata source=rest_device.go:61 msg="invalid OperatingState \"\""
level=ERROR ts=2019-04-24T16:10:00.45401Z app=edgex-core-metadata source=rest_device.go:61 msg="invalid OperatingState \"\""
level=ERROR ts=2019-04-24T16:10:00.453853Z app=edgex-core-metadata source=rest_device.go:61 msg="invalid OperatingState \"\""
level=ERROR ts=2019-04-24T16:10:00.454341Z app=edgex-core-metadata source=rest_device.go:61 msg="invalid OperatingState \"\""
level=ERROR ts=2019-04-24T16:10:00.454429Z app=edgex-core-metadata source=rest_device.go:61 msg="invalid OperatingState \"\""
level=ERROR ts=2019-04-24T16:10:00.454562Z app=edgex-core-metadata source=rest_device.go:61 msg="invalid OperatingState \"\""
level=ERROR ts=2019-04-24T16:10:00.454575Z app=edgex-core-metadata source=rest_device.go:61 msg="invalid OperatingState \"\""
level=ERROR ts=2019-04-24T16:10:00.454587Z app=edgex-core-metadata source=rest_device.go:61 msg="invalid OperatingState \"\""
level=ERROR ts=2019-04-24T16:10:00.454688Z app=edgex-core-metadata source=rest_device.go:61 msg="invalid OperatingState \"\""
level=ERROR ts=2019-04-24T16:10:00.454721Z app=edgex-core-metadata source=rest_device.go:61 msg="invalid OperatingState \"\""
level=ERROR ts=2019-04-24T16:10:00.454847Z app=edgex-core-metadata source=rest_device.go:61 msg="invalid OperatingState \"\""
level=ERROR ts=2019-04-24T16:10:00.455018Z app=edgex-core-metadata source=rest_device.go:61 msg="invalid OperatingState \"\""
level=ERROR ts=2019-04-24T16:10:00.455055Z app=edgex-core-metadata source=rest_device.go:61 msg="invalid OperatingState \"\""
level=ERROR ts=2019-04-24T16:10:00.455148Z app=edgex-core-metadata source=rest_device.go:61 msg="invalid OperatingState \"\""
level=ERROR ts=2019-04-24T16:10:00.45545Z app=edgex-core-metadata source=rest_device.go:61 msg="invalid OperatingState \"\""
level=ERROR ts=2019-04-24T16:10:00.993425Z app=edgex-core-metadata source=rest_provisionwatcher.go:306 msg="invalid OperatingState \"\""
level=ERROR ts=2019-04-24T16:10:00.99348Z app=edgex-core-metadata source=rest_provisionwatcher.go:306 msg="invalid OperatingState \"\""
level=ERROR ts=2019-04-24T16:10:00.993502Z app=edgex-core-metadata source=rest_provisionwatcher.go:306 msg="invalid OperatingState \"\""
```

My ask is to please ensure the following
- For any model that has an OperatingState property, that property needs to be populated with a correct value
- For any model that has an AdminState property, that property needs to be populated with a correct value
- For any model corresponding to an EdgeX entity (device, device profile, addressable, etc) on create, it needs to have a name. On update, it needs to have either an ID or a name.

What is your preferred method for addressing this? Would you like to do a pro-active review of the scripts to ensure required properties are populated? Or would you like me to proceed with the above integration and perform fixes based on what tests break? Since the imports don't even run successfully, A LOT of tests will fail -- if not all of them. Please advise ASAP.

**Comment by tsconn23** [comment]
FYI edgex-go PR has been created
https://github.com/edgexfoundry/edgex-go/pull/1284

**Comment by weichou1229** [comment]
@tsconn23  I check the test script, we have OperatingState, AdminState in those [device entities](ing/blob/master/bin/postman-test/collections/core-metadata-importer.postman_collection.json#L1938), and other entities have a name field.  

The problem was the nested object.
1. device profile: CoreCommands should define without reference $id ( we will fix it from the test script)
```
{
  "name": "test profile",
  "manufacturer": "Honeywell",
  ...
  "description": "BACnet Honeywell thermostats",
  "deviceCommands": [...],
  "origin": 1471806386919,
  "coreCommands": [
    {
      "$ref": "command",
      "$id": {
        "$oid": "57f38597e4b060e268aeb05a"
      }
    }
  ]
}
```

2. device: nested object only give a name
```
{
  "name": "cartachometer",
  ...
  ...
  "service": {
   "name": "car tachometer device service"
  },
  "profile": {
    "name": "car tachometer profile"
  }
},
```
But when I **replace the device service with the entire entity** and then it will work.
```
{
  "name": "cartachometer",
  ...
  "service": {
    "adminState": "unlocked",
    "operatingState": "enabled",
    "name": "car tachometer device service",
    "description": "manage car tachometer",
    "lastConnected": 0,
    "lastReported": 0,
    "labels": [
      "car",
      "tachometer"
    ],
    "origin": 1471806386921,
    "addressable": {
      "name": "tachometer address"
    }
  },
  "profile": {
    "name": "car tachometer profile"
  }
}
```

Do you have any idea about that?  Should I add the device with entire device service entity?

**Comment by tsconn23** [comment]
Yes, it's the nested entities that are the problem. Your solution sounds good. I'm concerned about the timing. If you're OK with the notice that tests will break once the edgex-go PR is merged, then we can proceed independently.

**Comment by weichou1229** [comment]
I thought to remove the ref $id in CoreCommands is OK.

But the device entity is a problem, it means the API will break with this general usage:
```
curl localhost:48081/api/v1/device -H "Content-Type:application/json"
 -X POST  \
   -d '{
           "name":"Variable Speed motor3",
           "description":"MicroMax Variable Speed Motor",
           "adminState":"UNLOCKED",
           "operatingState":"ENABLED",
           "addressable":{"name":"Motor"},
           "labels":["motor","modbus"],
           "service":{"name":"edgex-device-modbus"},
           "profile":{"name":"Network Power Meter3"}
}'
```

So, do you mean I need to add the device with entire device service entity?

**Comment by tsconn23** [comment]
Yes. A large type like Device that has nested child types has to have all required fields specified. So for the device you would need a minimum of the required fields for Addressable, AdminState, OperatingState, Service and Profile -- just like you've done above.

FWIW I've presented a proposal in the Core WG that would simplify requests, using a specific type for the API request that doesn't require this hugely nested structure. But this is where we are right now. I expect we'll be discussing refactoring next week in Seoul.

**Comment by weichou1229** [comment]
Ok, I get it now,  we will modify the test script, thanks.

1.  Remove the CoreCommands ref $id.
2. Add the required fields: OperatingState, AdminState.
Example:
```
{  
   "name" :"Air conditioner",
   "description":"Home automation system",
   "adminState":"UNLOCKED",
   "operatingState":"ENABLED",
   "protocols":{
      "modbus-tcp":{
         "host":"localhost",
         "port":"1234",
         "unitID":"1"
      }
   },
   "labels":[  
      "home",
      "hvac"
   ],
   "service":{  
      "name":"aeroplane tachometer device service",
      "adminState":"UNLOCKED",
      "operatingState":"ENABLED",
      "addressable":{
	  "name":"hvac telxsi thermo address"
      }
   },
   "profile":{  
      "name":"variable speed motor profile"
   }
}
```
