### ISSUE TITLE
Update core-command-importer.postman_collection.json to use new DeviceProfile properties

### ISSUE THREAD

**Issue by difince** [edgexfoundry/blackbox-testing#220]
In a while DeviceProfile properties have been renamed [see](https://github.com/edgexfoundry/go-mod-core-contracts/issues/59) :
Resources --> DeviceCommands
Commands --> CoreCommands

Related with this already closed [Issue](https://github.com/edgexfoundry/blackbox-testing/issues/197)

[core-command-importer.postman_collection.json](https://github.com/edgexfoundry/blackbox-testing/blob/79a8e13a3291aabf71df7e830823151b535c4688/bin/postman-test/collections/core-command-importer.postman_collection.json#L347) imports DeviceProfile and needs to be updated accordingly

**Comment by difince** [comment]
@tsconn23 could you assign it to me

**Comment by cloudxxx8** [comment]
@difince has assigned to you
thanks for taking care of this
