### ISSUE TITLE
Add tests for new metadata endpoint restGetCommandsByDeviceId

### ISSUE THREAD

**Issue by difince** [edgexfoundry/blackbox-testing#250]
New metadata endpoint is added: [restGetCommandsByDeviceId](https://github.com/edgexfoundry/edgex-go/blob/03f28e5980c37459c208a296556b0d148bea68db/internal/core/metadata/rest_command.go#L83).
Tests need to be added for that endpoint

**Comment by difince** [comment]
Could you assign this issue to me

**Comment by cloudxxx8** [comment]
thanks, @difince
