### ISSUE TITLE
Enhancement: Add helper functions for testing

### ISSUE THREAD

**Issue by mkbhanda** [edgexfoundry/blackbox-testing#252]
Routinely we test for HTTP response code, response time, presence of certain headers such as content type. Would be nice to have a library of a few helper functions for these and write tests that leverage these. If response time could be an environment variable it further lets us easily focus on code paths that might need revisiting to reach new goals.

**Comment by cloudxxx8** [comment]
@mkbhanda thanks for the suggestion.  we will make this helper function in new blackbox test (edgex-taf)

**Comment by jinlinGuan** [comment]
Move this issue to [edgexfoundry/edgex-taf#19](https://github.com/edgexfoundry/edgex-taf/issues/19)
