### ISSUE TITLE
New Test: Value Descriptor Usage Route

### ISSUE THREAD

**Issue by tsconn23** [edgexfoundry/blackbox-testing#253]
Tracking need for a test to verify functionality against the following new endpoint in core-data.

https://github.com/edgexfoundry/edgex-go/issues/1583

**Comment by jinlinGuan** [comment]
This issue will be handled after Value Descriptor API design is confirmed.

**Comment by jpwhitemn** [comment]
Given value descriptor is going away soon, closing this issue out.
