### ISSUE TITLE
Postman - testing (core-command)

### ISSUE THREAD

**Issue by odyslam** [edgexfoundry/blackbox-testing#259]
Incomplete core-command url regarding the core-command service and more specifically the device/device_id/command/command_id.

It creates a disparity with the API walkthrough that is illustrated in the docs, could create confusion.

**Comment by cloudxxx8** [comment]
The blackbox test is not based on the API walkthrough.
We are working on the new blacktest framework and will make it more look like a spec.
If you thought there is any important test needs to be added here, please specify the cases clearly.
Thanks for reporting this.

**Comment by odyslam** [comment]
I can't say which tests are important since I am don't have any experience, but I think that the postman collection should include the entirety of the APIs offered by edgex foundry.

At least, make it clear that the collection offers testing for a faction of the API (the most important perhaps) and thus the full API can be found [here]. I think it would greatly improve the user experience.

Thank you so much for taking the time to reply :)

**Comment by cloudxxx8** [comment]
right, it covered the complete API, but sometimes new API comes up.  Could you please indicate which API you found it is missing?  Is it the same as this one?
https://github.com/edgexfoundry/blackbox-testing/issues/203

**Comment by odyslam** [comment]
The API I was testing was in core-command
 :/device/device_id/command/command_id OR /device/name/device_name/command/command_name.

Cheers! :)
