### ISSUE TITLE
Add minor version backward compatibility test

### ISSUE THREAD

**Issue by cloudxxx8** [edgexfoundry/blackbox-testing#264]
Please see more detail in this document
https://wiki.edgexfoundry.org/download/attachments/329472/Minor-Release-Compatibility-Testing-v1.pdf?version=1&modificationDate=1566830165128&api=v2

**Comment by jinlinGuan** [comment]
This issue will be handled after Geneva version number is confirmed.

**Comment by cloudxxx8** [comment]
resolved by https://github.com/edgexfoundry/edgex-taf/pull/63
