### ISSUE TITLE
connection refused while trying to install blackbox testing scripts on ubuntu

### ISSUE THREAD

**Issue by gianpaolof** [edgexfoundry/blackbox-testing#270]
Hello
after cloning the repo, modifying the shell scripts as per the document and
running %>bash deploy-edgeX.sh

I got these errors:
![immagine](https://user-images.githubusercontent.com/6586650/64685365-2781c400-d487-11e9-978c-e9a346d5d280.png)

I'm on a Ubuntu VM on Win 10

Gianpaolo

**Comment by cloudxxx8** [comment]
could you please try again? it looks like a server issue.
Could you please try to run `docker-compose pull` with the nightly build docker-compose file without the shell script?
https://github.com/edgexfoundry/developer-scripts/tree/master/releases/nightly-build/compose-files

**Comment by gianpaolof** [comment]
> 
> 
> could you please try again? it looks like a server issue.
> Could you please try to run `docker-compose pull` with the nightly build docker-compose file without the shell script?
> https://github.com/edgexfoundry/developer-scripts/tree/master/releases/nightly-build/compose-files

Hello
the sripts gives me the same errors as before.

the output of the pull with that yaml is this:

![immagine](https://user-images.githubusercontent.com/6586650/65232139-efa2fe00-dad0-11e9-9fa0-bcca4dca5bb6.png)

**Comment by gianpaolof** [comment]
if that may help, other errors at the end of the pull

![immagine](https://user-images.githubusercontent.com/6586650/65232525-97b8c700-dad1-11e9-8060-df23ba266f43.png)

**Comment by cloudxxx8** [comment]
it obviously you can't access our nexus server.  are you under the firewall or in China?
the workaround is to replace all the image URL in the docker-compose file to the release version.
https://github.com/edgexfoundry/developer-scripts/tree/master/releases/edinburgh/compose-files

**Comment by cloudxxx8** [comment]
please update the bin/env.sh

**Comment by gianpaolof** [comment]
I'm  behind a proxy in Italy. Edinburgh has always been ok, I'm able to pull those images.

How should I update the env.sh? for example this line in the env.sh :
export volume=nexus3.edgexfoundry.org:10004/docker-edgex-volume:1.0.0

**Comment by cloudxxx8** [comment]
It looks like the nexus server is blocked
According to the image URL in Edinburgh docker-compose file
https://github.com/edgexfoundry/developer-scripts/blob/master/releases/edinburgh/compose-files/docker-compose-edinburgh-1.0.1.yml#L32
You should modify to
`export volume=edgexfoundry/docker-edgex-volume:1.0.0`

**Comment by gianpaolof** [comment]
I'm getting there....

do you know how to stop mongodb related services?
I have used a script provided by edgex and it loads some services:
db.serviceMapping.insert( { serviceName: "coredata", serviceUrl: "http://localhost:48080/" });
db.serviceMapping.insert( { serviceName: "metadata", serviceUrl: "http://localhost:48081/" });
db.serviceMapping.insert( { serviceName: "command", serviceUrl: "http://localhost:48082/" });
db.serviceMapping.insert( { serviceName: "rules", serviceUrl: "http://localhost:48084/" });
db.serviceMapping.insert( { serviceName: "notifications", serviceUrl: "http://localhost:48060/" });
db.serviceMapping.insert( { serviceName: "logging", serviceUrl: "http://localhost:48061/" });
db.serviceMapping.insert( { serviceName: "exportclient", serviceUrl: "http://localhost:48071/" });

I don't know how to stop them without rebooting the machine :/

**Comment by gianpaolof** [comment]
I killed the services and rerun the script. It's working. thank you for your help

**Comment by cloudxxx8** [comment]
it would be different from running Mongo natively or on docker container.
Please let me know if you still have the issue.
