### ISSUE TITLE
Core-command tests fail

### ISSUE THREAD

**Issue by AnthonyMBonafide** [edgexfoundry/blackbox-testing#276]
Some core command tests are failing. It seems like the issues are related to devices not being created during the import stage of the test run. The tests are performing GET operations for the `Random-Integer-Device` and `Random-Boolean-Device` but they were never created when using the `run.sh` script. Please see comments in the `edgex-go` issue https://github.com/edgexfoundry/edgex-go/pull/1850 for more details

**Comment by cherrycl** [comment]
@AnthonyMBonafide The device "Random-Integer-Device" and "Random-Boolean-Device" was created by device-virtual service. When running the related testcases, the device-virtual should be running.

**Comment by michaelestrin** [comment]
Confirmed.
