### ISSUE TITLE
BlackBox tests on Cavium arm64 box are failing currently

### ISSUE THREAD

**Issue by JPWKU** [edgexfoundry/blackbox-testing#28]
For example: https://jenkins.edgexfoundry.org/view/blackbox-testing/job/blackbox-testing-cavium-arm64-master/2/console

In particular this line in the console logs: `[1BThe mongoSeed variable is not set. Defaulting to a blank string.`  
I believe the fix is to add an entry for `mongoSeed` in `blackbox-testing/bin/arm64_env.sh`

**Comment by andyf1967** [comment]
@weichou1229 @cloudxxx8 what are your thoughts on this issue. Do you agree with @JPWKU proposed fix ?

**Comment by weichou1229** [comment]
@andyf1967 yes , he's right ,
but consul and mongo-seed are not require deploy independently  in https://wiki.edgexfoundry.org/display/FA/Get+EdgeX+Foundry+-+Users  ,
must update https://github.com/edgexfoundry/blackbox-testing/blob/master/deploy-edgeX.sh and https://github.com/edgexfoundry/blackbox-testing/blob/master/docker-compose.yml to meet the document

**Comment by cloudxxx8** [comment]
@JPWKU it looks like the mongo-seed environment variable is missing in https://github.com/edgexfoundry/blackbox-testing/blob/master/bin/arm64_env.sh
In current design, we only need "mongo-seed" instead of "mongo" docker image.
Do we have mongo-seed docker image for arm64?

**Comment by cloudxxx8** [comment]
fixed by https://github.com/edgexfoundry/blackbox-testing/pull/42/files
