### ISSUE TITLE
blackbox testing cases are failed on blackbox centOS image

### ISSUE THREAD

**Issue by michaelestrin** [edgexfoundry/blackbox-testing#305]
From @tingyuz:

> Currently some blackbox testing cases are failed on blackbox centOS image, most of which are related to proxy health checking. Checking the log on bb testing centOS image and noticed that KONG was failed to start.
> Here is related logs:
> 
> 09:32:34 ------- kong ------
> 09:32:34 chmod: /proc/self/fd/1: Permission denied
> 09:32:34 chmod: /proc/self/fd/1: Permission denied
> 
> After some research we found that KONG 1.0.3 is not working on centOS 7 ( issue opened at KONG here: Kong/docker-kong#274). Since KONG was failed to start, these testing cases were failed.
>
> These issues are not related to code base of edgex-go, but environment issue of blackbox testing. I would suggest to move these issues under blackbox testing and put these limitation into release guide, and mark them as unresolved issues for next release of blackbox testing.

**Comment by michaelestrin** [comment]
@cloudxxx8 Is this something you can help us get addressed (by working with DevOps to address the issue prior to next week's release of Fuji)?

**Comment by michaelestrin** [comment]
> I would suggest to move these issues under blackbox testing and **put these limitation into release guide**, and mark them as unresolved issues for next release of blackbox testing.

@tingyuz was the release guide updated? If so, can you link to the corresponding issue?  If not, can you create a corresponding issue and ensure it is assigned and completed prior to next week's Fuji release?

**Comment by cloudxxx8** [comment]
ok, my team member @judehung is working on this issue

**Comment by lranjbar** [comment]
@cloudxxx8 I was able to triage and solve the issue of Kong not starting on CentOS.
