### ISSUE TITLE
remove insecureSkipVerify arg

### ISSUE THREAD

**Issue by michaelestrin** [edgexfoundry/blackbox-testing#307]
Synchronize changes made in https://github.com/edgexfoundry/developer-scripts/pull/159 to blackbox-testing's docker-compose file.

**Comment by anonymouse64** [comment]
I won't have time to work on this issue

**Comment by cloudxxx8** [comment]
this should also be fixed by #295

**Comment by michaelestrin** [comment]
@cloudxxx8 Do you have an estimated time when #295 will be completed? This is work that should have been done when the corresponding changes were made in the developer-scripts repository. 
 If #295 is expected to be completed within the next week, I'd say we could wait. Otherwise, my ask is for @jim-wang-intel, @bnevis-i, or @tingyuz to port the work done in https://github.com/edgexfoundry/developer-scripts/pull/159 to the blackbox testing repository early this week.  We need to strive to ensure the work that's completed includes all of the areas of the system that require changing; https://github.com/edgexfoundry/developer-scripts/pull/159 didn't get ported at the time it was completed and it should have been.

**Comment by cloudxxx8** [comment]
#295 has to be completed by next week
add @jinlinGuan and @cherrycl for awareness

**Comment by michaelestrin** [comment]
#295 is still in flight as of the date/time of this entry.  @jim-wang-intel, @tingyuz, @bnevis-i -- please do the necessary work to get this change into blackbox-testing's copy of the docker-compose file so we can ensure security-related tests run properly between now and when #295 is merged.

**Comment by bnevis-i** [comment]
Switch removed in https://github.com/edgexfoundry/blackbox-testing/pull/349.

**Comment by michaelestrin** [comment]
Closed.  Should be addressed by https://github.com/edgexfoundry/blackbox-testing/pull/349.
