### ISSUE TITLE
ARM blackbox-testing failing in run.sh on both master and fuji branches

### ISSUE THREAD

**Issue by lranjbar** [edgexfoundry/blackbox-testing#322]
Blackbox testing runs are failing while running the shell script `bin/run.sh`

Here is the error on fuji:
```
10:31:54 ./run.sh: line 131: 16569 Terminated              testAll
10:31:54      16570                       | tee $EDGEXLOGSPATH
```

On master
```
10:31:54 ./run.sh: line 131: 16569 Terminated              testAll
10:31:54      16570                       | tee $EDGEXLOGSPATH
```

https://jenkins.edgexfoundry.org/view/blackbox-testing/job/blackbox-testing-security-ubuntu18.04-docker-arm64-4c-2g-master/316/console

**Comment by lranjbar** [comment]
@cloudxxx8 We have the shell scripts failing, I think we should prioritize this.

**Comment by anonymouse64** [comment]
I have no idea what the run.sh script does so I can't be of much help here unfortunately

**Comment by lranjbar** [comment]
Digging into this with @anonymouse64 and @michaelestrin This is actually a duplicate of #302
