### ISSUE TITLE
Secretstore testcases failed on ARM platform for Fuji release

### ISSUE THREAD

**Issue by cherrycl** [edgexfoundry/blackbox-testing#337]
Below [BlackBox testing log](https://jenkins.edgexfoundry.org/view/blackbox-testing/job/blackbox-testing-security-ubuntu18.04-docker-arm64-4c-2g-fuji/32/consoleFull) for reference. 

> 21:26:13 ❏ secretstore
> 21:26:13 ↳ 01 health check
> 21:26:13   GET https://edgex-vault:8200/v1/sys/health [errored]
> 21:26:13      write EPROTO 281473131878792:error:1414D17A:SSL routines:tls12_check_peer_sigalg:wrong curve:t1_lib.c:1101:
> 21:26:13 
> 21:26:13   2. Secret store health check
> 21:26:13 
> 21:26:13 ↳ 02 mising vault keytest
> 21:26:13   GET https://edgex-vault:8200/v1/sys/key-status [errored]
> 21:26:13      write EPROTO 281473131878792:error:1414D17A:SSL routines:tls12_check_peer_sigalg:wrong curve:t1_lib.c:1101:
> 21:26:13 
> 21:26:13   4. Missing secret store access check
> 21:26:13 
> 21:26:13 ↳ 03 unauthorized vault key test
> 21:26:13   GET https://edgex-vault:8200/v1/sys/key-status [errored]
> 21:26:13      write EPROTO 281473131878792:error:1414D17A:SSL routines:tls12_check_peer_sigalg:wrong curve:t1_lib.c:1101:
> 21:26:13 
> 21:26:13   6. Unauthorized secret store access check

**Comment by cloudxxx8** [comment]
fixed by #337, waiting for making the same fix in master
