### ISSUE TITLE
Missing tests for CBOR events

### ISSUE THREAD

**Issue by AnthonyMBonafide** [edgexfoundry/blackbox-testing#338]
Currently there are no tests exercising the functionality for creating an event that is of the CBOR type. This is necessary since there is logic which only applies to CBOR events, such as creating checksums.

https://github.com/edgexfoundry/edgex-go/blob/c1ecbde72d6d2056e62b4c068ee23d573ebbe189/internal/core/data/io.go#L74-L82

**Comment by jinlinGuan** [comment]
Move this issue to [edgexfoundry/edgex-taf#21](https://github.com/edgexfoundry/edgex-taf/issues/21)

**Comment by cloudxxx8** [comment]
fixed by https://github.com/edgexfoundry/blackbox-testing/pull/416 and https://github.com/edgexfoundry/blackbox-testing/pull/415
