### ISSUE TITLE
Update the blackbox-testing docker-compose file

### ISSUE THREAD

**Issue by michaelestrin** [edgexfoundry/blackbox-testing#342]
Update the blackbox-testing docker-compose file to reflect the changes made by https://github.com/edgexfoundry/developer-scripts/pull/184

**Comment by cloudxxx8** [comment]
@jinlinGuan is working on #295 , so it will be consistent soon

**Comment by michaelestrin** [comment]
@cloudxxx8 Do you have an estimated time when #295 will be completed?  The master branch's security versions of the blackbox tests are currently broken and should be fixed as quickly as possible.  If #295 is expected to be completed within the next week, I'd say we could wait.  Otherwise, my ask is for @jim-wang-intel, @bnevis-i, or @tingyuz to port the work done in https://github.com/edgexfoundry/developer-scripts/pull/184 to the blackbox testing repository early this week to get the blackbox tests up and functioning again.

**Comment by cloudxxx8** [comment]
#295 has to be completed by next week
add @jinlinGuan and @cherrycl for awareness

**Comment by michaelestrin** [comment]
#295 is still in flight as of the date/time of this entry.  @jim-wang-intel, @tingyuz, @bnevis-i -- please do the necessary work to get this change into blackbox-testing's copy of the docker-compose file so we can ensure security-related tests run properly between now and when #295 is merged.

**Comment by bnevis-i** [comment]
https://github.com/edgexfoundry/blackbox-testing/pull/349 was submitted on Friday and is still awaiting review and merge.

**Comment by michaelestrin** [comment]
#349 made progress but didn't fix the build.  Now seeing following:

![image](https://user-images.githubusercontent.com/464327/71039277-5ee8b800-20e9-11ea-9073-95a2e2c0142a.png)
