### ISSUE TITLE
Modify API path to go through Kong when security is enabled

### ISSUE THREAD

**Issue by cloudxxx8** [edgexfoundry/blackbox-testing#343]
Currently, black box tests with security services running - checks all the APIs (using the docker-compose file that does include security services).  However, these tests don't actually try to use the service APIs through Kong.  It tests the same APIs as #1, and just makes sure security services are not otherwise breaking anything.  We should have black box tests hit the public facing APIs (for example the device service APIs would never be called directly by 3rd parties outside of EdgeX and so they are not exposed through Kong) with security services running and have these calls go through the API gateway (Kong).  This is a much better test of whether the API gateway is working properly and is configured correctly.

**Comment by cherrycl** [comment]
This issue was fixed by #371
