### ISSUE TITLE
Value descriptor tests timing out on Blackbox tests (Security runs)

### ISSUE THREAD

**Issue by lranjbar** [edgexfoundry/blackbox-testing#347]
After updating the images to point at the new images built off the master branch we have the blackbox tests timing out again.

Full description here: https://github.com/edgexfoundry/edgex-go/issues/2220

@cloudxxx8 @tsconn23 @michaelestrin

**Comment by michaelestrin** [comment]
Security versions of builds [have been broken since we updated to master branch](https://edgexfoundry.slack.com/archives/CE5U62YHM/p1575660256218800).  

Related https://github.com/edgexfoundry/blackbox-testing/issues/343 and https://github.com/edgexfoundry/blackbox-testing/issues/342

**Comment by bnevis-i** [comment]
I am going to assume that the acceptance test for closing this ticket is a successful Allure report for: 
https://jenkins.edgexfoundry.org/view/blackbox-testing/job/blackbox-testing-security-centos7-blackbox-4c-2g-master/

Correct me if I am wrong.

**Comment by bnevis-i** [comment]
As per above test result link, this test is still failing due to timeout (but the test is now running again)

https://jenkins.edgexfoundry.org/view/blackbox-testing/job/blackbox-testing-security-centos7-blackbox-4c-2g-master/allure/#suites/0253696db23ccc01cc5ff962ab0371ef/6f975821ae78b559/

**Comment by bnevis-i** [comment]
This seems to be a core-data test. Going to sit on this for a few days and see if it is transient or recurrent.

**Comment by michaelestrin** [comment]
From my perspective, the failing Value Descriptor tests were a symptom and not the cause.  Now that you've gotten the security build running to completion again, I believe this issue can be safely closed. I'll leave it up to @bnevis-i to close it.

**Comment by lranjbar** [comment]
The only change with that build linked is that it is allowing other tests to run which is a step in the right direction. 

The previous builds aren't able to run the rest of the tests due to the timeout on the valueDescriptor tests:
#685 https://jenkins.edgexfoundry.org/blue/organizations/jenkins/blackbox-testing-centos7-blackbox-4c-2g-master/detail/blackbox-testing-centos7-blackbox-4c-2g-master/685/pipeline/
#686 https://jenkins.edgexfoundry.org/blue/organizations/jenkins/blackbox-testing-centos7-blackbox-4c-2g-master/detail/blackbox-testing-centos7-blackbox-4c-2g-master/686/pipeline/

If we want to close this issue and reopen the issue in edgex-go that would make more sense.

**Comment by bnevis-i** [comment]
From the logs above I can clearly see that the failure reference was due to containers failing (such as edgex-core-data) and thus DNS resolution failing.  Also there are the support-rulesengine failures in there as well.  All of these issues are fixed.

Old logs
```
core-data-importer



→ Import valueDescriptor

  GET http://edgex-core-data:48080/api/v1/ping [errored]

     getaddrinfo ENOTFOUND edgex-core-data edgex-core-data:48080

  POST http://edgex-core-data:48080/api/v1/valuedescriptor   POST http://edgex-core-data:48080/api/v1/valuedescriptor   POST http://edgex-core-data:48080/api/v1/valuedescriptor   POST http://edgex-core-data:48080/api/v1/valuedescriptor   POST http://edgex-core-data:48080/api/v1/valuedescriptor   POST http://edgex-core-data:48080/api/v1/valuedescriptor   POST http://edgex-core-data:48080/api/v1/valuedescriptor   POST http://edgex-core-data:48080/api/v1/valuedescriptor   POST http://edgex-core-data:48080/api/v1/valuedescriptor [errored]

     getaddrinfo ENOTFOUND edgex-core-data edgex-core-data:48080

[errored]

     getaddrinfo ENOTFOUND edgex-core-data edgex-core-data:48080

[errored]

     getaddrinfo ENOTFOUND edgex-core-data edgex-core-data:48080

[errored]

     getaddrinfo ENOTFOUND edgex-core-data edgex-core-data:48080

[errored]

     getaddrinfo ENOTFOUND edgex-core-data edgex-core-data:48080

[errored]

     getaddrinfo ENOTFOUND edgex-core-data edgex-core-data:48080

[errored]

     getaddrinfo ENOTFOUND edgex-core-data edgex-core-data:48080

[errored]

     getaddrinfo ENOTFOUND edgex-core-data edgex-core-data:48080

[errored]

     getaddrinfo ENOTFOUND edgex-core-data edgex-core-data:48080

Build timed out (after 60 minutes). Marking the build as failed.
```

New logs
```
core-data-importer

→ Import valueDescriptor
  GET http://edgex-core-data:48080/api/v1/ping [200 OK, 105B, 97ms]
  POST http://edgex-core-data:48080/api/v1/valuedescriptor   POST http://edgex-core-data:48080/api/v1/valuedescriptor   POST http://edgex-core-data:48080/api/v1/valuedescriptor   POST http://edgex-core-data:48080/api/v1/valuedescriptor   POST http://edgex-core-data:48080/api/v1/valuedescriptor   POST http://edgex-core-data:48080/api/v1/valuedescriptor   POST http://edgex-core-data:48080/api/v1/valuedescriptor   POST http://edgex-core-data:48080/api/v1/valuedescriptor   POST http://edgex-core-data:48080/api/v1/valuedescriptor [200 OK, 153B, 962ms]
[200 OK, 153B, 974ms]
[200 OK, 153B, 976ms]
[200 OK, 153B, 985ms]
[200 OK, 153B, 988ms]
[200 OK, 153B, 1051ms]
[200 OK, 153B, 1661ms]
[200 OK, 153B, 1665ms]
[200 OK, 153B, 1670ms]
```

Thus, the tests are now running.  I am in favor of closure.  @lranjbar do you agree?

**Comment by lranjbar** [comment]
Ok I see that blackbox-testing is running as expected now.
