### ISSUE TITLE
Security failing blackbox tests (x86_64)

### ISSUE THREAD

**Issue by bnevis-i** [edgexfoundry/blackbox-testing#368]
# 🐞 Bug Report

Failing tests from https://jenkins.edgexfoundry.org/view/blackbox-testing/job/blackbox-testing-security-centos7-blackbox-4c-2g-master/

### Description and Minimal Reproduction
| Status | Suite                                                                                   | Test Class            | Name                                       |
|--------|-----------------------------------------------------------------------------------------|-----------------------|--------------------------------------------|
| failed | apigateway / Proxy Check / 01 Unauthorized token proxy access test                      | SecurityServiceDocker | Unauthorized Coredata Access Failure       |
| failed | apigateway / Health Check / 05 port 8444 SSL admin port test                            | SecurityServiceDocker | Port 8444 served                           |
| failed | apigateway / Health Check / 03 port 8443 non-existing path test                         | SecurityServiceDocker | Port 8443 not served                       |
| failed | Test whether the virtual device service exists                                          | DeviceVirtual         | Response body is correct                   |
| failed | apigateway / Proxy Check / 02 invalid token proxy access test command                   | SecurityServiceDocker | Unauthorized Command Access Failure        |
| failed | apigateway / Health Check / 04 port 8443 SSL missing token test                         | SecurityServiceDocker | Port 8443 with missing token test          |
| failed | apigateway / Proxy Check / 05 POST reading test                                         | SecurityServiceDocker | Invalid POST Action                        |
| failed | apigateway / Health Check / 01 port 8000 missing token test                             | SecurityServiceDocker | Port 8000 with missing token test          |
| failed | Test the put value method                                                               | DeviceVirtual         | Response time is less than 600ms           |
| failed | device / http://localhost:48082/api/v1/device                                           | CoreCommand           | Status code is 200                         |
| failed | apigateway / Proxy Check / 03 invalid token proxy access test metadata - JWT Token test | SecurityServiceDocker | Unauthorized JWT token access failure test |
| failed | apigateway / Proxy Check / 04 reading error test                                        | SecurityServiceDocker | Invalid PUT Action                         |
| failed | apigateway / Health Check / 02 port 8001 admin port test                                | SecurityServiceDocker | Port 8001 served                           |

**Comment by bnevis-i** [comment]
Looks like kong didn't make it up all the way: 

```
------- kong ------
+ exec /consul/scripts/health kong-migrations
passing
chmod: changing permissions of '/proc/self/fd/1': Permission denied
chmod: changing permissions of '/proc/self/fd/2': Permission denied
nginx: [emerg] open() "/dev/stderr" failed (13: Permission denied)
------- edgex-proxy ------
+ exec /consul/scripts/health kong
critical
```

I think we've seen this before and it was fixed before by making sure we run the centos version of Kong.

We should add something to output the docker-compose that is being used because we have to patch it for CentOS compatibility and need to make sure that it worked.  (Evidence is indicating that our sed patch didn't work.)

**Comment by bnevis-i** [comment]
I think I know what this is... This other github comment: https://github.com/moby/moby/issues/ 31243 seems to suggest that a tty:true is needed for the kong container.  That is missing in the docker-compose scripts and was lost in the migration.

**Comment by bnevis-i** [comment]
PR submitted in developer-scripts to address what I believe is the issue (easy to confirm that tty: true was dropped in the docker compose when we migrated to developer-scripts)

**Comment by cloudxxx8** [comment]
thanks, @bnevis-i We have verified the fix works locally
Let's close this issue once it passes on Jenkins
