### ISSUE TITLE
Two testcases failing on all the platforms regardless of security

### ISSUE THREAD

**Issue by jinlinGuan** [edgexfoundry/blackbox-testing#373]
https://jenkins.edgexfoundry.org/view/blackbox-testing/job/blackbox-testing-security-centos7-blackbox-4c-2g-master/

 Suite | Test Class | Test Case | Detail
 -- | -- | -- | --
Test whether the virtual device service exists | DeviceVirtual | Response body is correct | expected 'master' to include '1.1.0'
device / http://localhost:48082/api/v1/device | CoreCommand | Status code is 200 | 500 Internal Server Error

**Comment by cloudxxx8** [comment]
@jinlinGuan please focus on the first one because the core working group is working on the second one
https://github.com/edgexfoundry/edgex-go/issues/2237

**Comment by jinlinGuan** [comment]
This PR [edgexfoundry/blackbox-testing/#378](https://github.com/edgexfoundry/blackbox-testing/pull/378) fixed the first failed testcase.

**Comment by brandonforster** [comment]
edgexfoundry/edgex-go#2237 is now closed and this should be fixed.

**Comment by cloudxxx8** [comment]
thank you for the notice, @brandonforster 
we will verify it and close this issue

**Comment by cloudxxx8** [comment]
verified this issue locally
