### ISSUE TITLE
The SMA operation "restart" fail on arm

### ISSUE THREAD

**Issue by cherrycl** [edgexfoundry/blackbox-testing#384]
[Jenkins log](https://jenkins.edgexfoundry.org/view/blackbox-testing/job/blackbox-testing-security-ubuntu18.04-docker-arm64-4c-2g-master/419/console)

20:31:28 ↳ restart_all_services
20:31:28   POST http://edgex-sys-mgmt-agent:48090/api/v1/operation [errored]
20:31:40      socket hang up
20:31:40   3. Status code is 200
20:31:40   4. Response time is less than 90000ms
20:31:40   5. Content-Type is application/json

**Comment by cherrycl** [comment]
@akramtexas The test passed on my ubuntu x86_64 env using the latest image but found it still failed on arm64.

**Comment by akramtexas** [comment]
@cherrycl I will investigate and report back on the anomalous behavior on the `ARM` build.

**Comment by akramtexas** [comment]
- I have sought to find what's different (duration-and-timing-wise in particular) about the `ARM64 build`, as compared to the `UBUNTU build`.
- The one data points I have is that, in general, the `ARM64 builds` run slower, as compared to the `UBUNTU builds`.
- Given that the investigation of the original issue had revealed that the Docker executable was the bottleneck ([as addressed per - Issue-372](https://github.com/edgexfoundry/blackbox-testing/issues/372#issuecomment-580610832)), and which was resolved by slightly increasing the `http.Server timeout` value, it is possible that the increased `http.Server timeout` value does not suffice for `ARM64 builds` (given that they run slower than `UBUNTU builds`). 
- So an approach is to increase the `http.Server timeout` value slightly more still and ascertain that this increase resolves the issue seen with `ARM64 builds`.

**Comment by akramtexas** [comment]
@michaelestrin - Referring to my preceding comment, and given that the outcome of `ARM64 builds` would of necessity have to be found by a triggered Jenkins build, each one triggered by submitting an update per increased `http.Server timeout` values (increasing that value slightly-more than the current value, incrementing successively by one second, until a value suffices for `ARM64 builds`). I couldn't think of a simpler approach than this... Thoughts, suggestions? Thanks!

**Comment by michaelestrin** [comment]
I believe timeout is currently set at 10 seconds:  https://github.com/edgexfoundry/edgex-go/blob/0a580629264ee501ee3be2916c9cbbe81faf93f2/cmd/sys-mgmt-agent/res/configuration.toml#L27

Double that.

**Comment by akramtexas** [comment]
> I believe timeout is currently set at 10 seconds: https://github.com/edgexfoundry/edgex-go/blob/0a580629264ee501ee3be2916c9cbbe81faf93f2/cmd/sys-mgmt-agent/res/configuration.toml#L27
> 
> Double that.

Excellent, I will make it so, and confirm that doing so resolves the issue 👍

**Comment by akramtexas** [comment]
@cherrycl This issue has been resolved and tested. 
- This issue required an update to the `edgex-go` repo (If interested, please see the details in [PR-2353](https://github.com/edgexfoundry/edgex-go/pull/2353)).
- Tested the fix via a new `ARM64 image` published to staging: https://jenkins.edgexfoundry.org/view/edgex-go/job/edgex-go-master-stage-go-arm/ and you can examine the console output of the `ARM64` blackbox-testing Jenkins build 
at https://jenkins.edgexfoundry.org/view/blackbox-testing/job/blackbox-testing-security-ubuntu18.04-docker-arm64-4c-2g-master/430/console where you will see the confirmation that the fix has resolved the issue:
```
12:21:10 ↳ restart_all_services
12:21:10   POST http://edgex-sys-mgmt-agent:48090/api/v1/operation [200 OK, 571B, 13.1s]
12:21:23   ✓  Status code is 200
12:21:23   ✓  Response time is less than 90000ms
12:21:23   ✓  Content-Type is application/json
```
- I'll leave this issue open for a few days, before we close it. Please let me know if you have any questions.

**Comment by cherrycl** [comment]
The restart tests passed on recently arm64 build. Close this issue. @akramtexas  Thanks for your help.
