### ISSUE TITLE
Core-Command blackbox tests failing on master branch

### ISSUE THREAD

**Issue by jinlinGuan** [edgexfoundry/blackbox-testing#387]
20:59:46 ❏ device
20:59:46 ↳ http://localhost:48082/api/v1/device
**20:59:46   GET http://edgex-core-command:48082/api/v1/device [500 Internal Server Error, 206B, 178ms]**
20:59:46   1. Status code is 200

20:59:46 ↳ 17 http://localhost:48082/api/v1/device/:id
**20:59:46   GET http://edgex-core-command:48082/api/v1/device/name/Livingroom automation [500 Internal Server Error, 233B, 9ms]
20:59:46   GET http://edgex-core-command:48082/api/v1/device/{{getDeviceById}} [500 Internal Server Error, 232B, 13ms]**
20:59:46   2. Status code is 200

20:59:46 ↳ 20_200 http://localhost:48082/api/v1/device/:id/command/{commandId}
**20:59:46   GET http://edgex-core-command:48082/api/v1/device/name/Random-Boolean-Device [500 Internal Server Error, 233B, 6ms]
20:59:47   GET http://edgex-core-command:48082/api/v1/device/{{getDeviceById}}/command/{{getCommandById}} [500 Internal Server Error, 232B, 6ms]**
20:59:47   3. Status code is 200

20:59:47 ↳ 21_200 http://localhost:48082/api/v1/device/:id/command/{commandId}
**20:59:47   GET http://edgex-core-command:48082/api/v1/device/name/Random-Integer-Device [500 Internal Server Error, 233B, 6ms]
20:59:47   PUT http://edgex-core-command:48082/api/v1/device/{{getDeviceById}}/command/{{getCommandById}} [500 Internal Server Error, 232B, 7ms]**
20:59:47   4. Status code is 200

20:59:47 ↳ http://localhost:48082/api/v1/device/name/:name
**20:59:47   GET http://edgex-core-command:48082/api/v1/device/name/Livingroom automation [500 Internal Server Error, 233B, 5ms]**
20:59:47   5. Status code is 200

20:59:47 ↳ 30_200 http://localhost:48082/api/v1/device/name/{name}/command/{commandname}
**20:59:47   GET http://edgex-core-command:48082/api/v1/device/name/Random-Integer-Device [500 Internal Server Error, 233B, 5ms]
20:59:47   GET http://edgex-core-command:48082/api/v1/device/name/Random-Integer-Device/command/{{CommandName}} [500 Internal Server Error, 233B, 6ms]**
20:59:47   6. Status code is 200

20:59:47 ↳ 31_200 http://localhost:48082/api/v1/device/name/{name}/command/{commandname}
**20:59:47   GET http://edgex-core-command:48082/api/v1/device/name/Random-Integer-Device [500 Internal Server Error, 233B, 6ms]
20:59:47   PUT http://edgex-core-command:48082/api/v1/device/name/Random-Integer-Device/command/{{CommandName}} [500 Internal Server Error, 233B, 6ms]**
20:59:47   7. Status code is 200

20:59:50 ❏ device_error_4xx
20:59:50 ↳ 21_404 http://localhost:48082/api/v1/device/:id/command/{commandId}
**20:59:50   PUT http://edgex-core-command:48082/api/v1/device/a6f928f3-5737-40c5-99e6-0db366c9434d/command/53276951-0f7f-4cf5-b8d7-73ded9095d0a [500 Internal Server Error, 243B, 118ms]**
20:59:51   1. Status code is 404

20:59:51 ↳ 21_423 http://localhost:48082/api/v1/device/:id/command/{commandId}
**20:59:51   GET http://edgex-core-command:48082/api/v1/device/name/aeroplanetachometer [500 Internal Server Error, 231B, 9ms]
20:59:51   PUT http://edgex-core-command:48082/api/v1/device/{{deviceGetRequestIdWithStateLocked}}/command/8654ceff-1e66-4b58-b7d7-7c449ad174fc [500 Internal Server Error, 252B, 12ms]**
20:59:51   2. Status code is 423

20:59:51 ↳ 18  http://localhost:48082/api/v1/device/:id
**20:59:51   GET http://edgex-core-command:48082/api/v1/device/8fbfbf8d-1505-48ae-af9e-dc6b532889b4 [500 Internal Server Error, 243B, 6ms]**
20:59:51   3. Status code is 404

20:59:51 ↳ 20_404 http://localhost:48082/api/v1/device/:id/command/{commandId}
**20:59:51   GET http://edgex-core-command:48082/api/v1/device/a6f928f3-5737-40c5-99e6-0db366c9434d/command/8654ceff-1e66-4b58-b7d7-7c449ad174fc [500 Internal Server Error, 243B, 6ms]**
20:59:51   4. Status code is 404

20:59:51 ↳ 20_423 http://localhost:48082/api/v1/device/:id/command/{commandId}
**20:59:51   GET http://edgex-core-command:48082/api/v1/device/name/test device-2 for command [500 Internal Server Error, 237B, 6ms]
20:59:51   GET http://edgex-core-command:48082/api/v1/device/{{deviceLockedId}}/command/8654ceff-1e66-4b58-b7d7-7c449ad174fc [500 Internal Server Error, 233B, 5ms]**
20:59:51   5. Status code is 423

20:59:51 ↳ 27  http://localhost:48082/api/v1/device/name/{name}
**20:59:51   GET http://edgex-core-command:48082/api/v1/device/name/Invalid_device_name [500 Internal Server Error, 231B, 6ms]**
20:59:51   6. Status code is 404

20:59:51 ↳ 30_404 http://localhost:48082/api/v1/device/name/{name}/command/{commandname}
**20:59:51   GET http://edgex-core-command:48082/api/v1/device/name/livingroomthermostat/command/coolingpointinvalid [500 Internal Server Error, 232B, 5ms]**
20:59:51   7. Status code is 404

20:59:51 ↳ 31_404 http://localhost:48082/api/v1/device/name/{name}/command/{commandname}
**20:59:51   PUT http://edgex-core-command:48082/api/v1/device/name/Livingroom/command/{{commandName}} [500 Internal Server Error, 222B, 7ms]**
20:59:51   8. Status code is 404

20:59:51 ↳ 30_423 http://localhost:48082/api/v1/device/name/{name}/command/{commandname}
**20:59:51   GET http://edgex-core-command:48082/api/v1/device/name/Livingroom automation/command/cooling point [500 Internal Server Error, 233B, 8ms]**
20:59:51   9. Status code is 423

20:59:51 ↳ 31_423 http://localhost:48082/api/v1/device/name/{name}/command/{commandname}
**20:59:51   PUT http://edgex-core-command:48082/api/v1/device/name/Livingroom automation/command/cooling point [500 Internal Server Error, 233B, 6ms]**
20:59:51  10. Status code is 423

The log of core-command:
<img width="1433" alt="image" src="https://user-images.githubusercontent.com/55377716/74517409-06992f80-4f4d-11ea-857c-4d76d39b4ad5.png">

**Comment by cloudxxx8** [comment]
verified passed locally
