### ISSUE TITLE
Security jenkins jobs failed on importing data by core-data

### ISSUE THREAD

**Issue by cherrycl** [edgexfoundry/blackbox-testing#389]
20:37:11 core-data-importer
20:37:11 
20:37:11 → Import valueDescriptor
20:37:11   GET https://kong:8443/coredata/api/v1/ping [errored]
20:37:11      connect ECONNREFUSED 172.17.0.8:8443
20:37:11   POST https://kong:8443/coredata/api/v1/valuedescriptor   POST https://kong:8443/coredata/api/v1/valuedescriptor   POST https://kong:8443/coredata/api/v1/valuedescriptor   POST https://kong:8443/coredata/api/v1/valuedescriptor   POST https://kong:8443/coredata/api/v1/valuedescriptor   POST https://kong:8443/coredata/api/v1/valuedescriptor   POST https://kong:8443/coredata/api/v1/valuedescriptor   POST https://kong:8443/coredata/api/v1/valuedescriptor   POST https://kong:8443/coredata/api/v1/valuedescriptor [errored]
20:37:11      connect ECONNREFUSED 172.17.0.8:8443
20:37:11 [errored]
20:37:11      connect ECONNREFUSED 172.17.0.8:8443
20:37:11 [errored]
20:37:11      connect ECONNREFUSED 172.17.0.8:8443
20:37:11 [errored]
20:37:11      connect ECONNREFUSED 172.17.0.8:8443
20:37:11 [errored]
20:37:11      connect ECONNREFUSED 172.17.0.8:8443
20:37:11 [errored]
20:37:11      connect ECONNREFUSED 172.17.0.8:8443
20:37:11 [errored]
20:37:11      connect ECONNREFUSED 172.17.0.8:8443
20:37:11 [errored]
20:37:11      connect ECONNREFUSED 172.17.0.8:8443
20:37:11 [errored]
20:37:11      connect ECONNREFUSED 172.17.0.8:8443
21:33:01 Build timed out (after 60 minutes). Marking the build as failed.

**Comment by cloudxxx8** [comment]
@tingyuz @bnevis-i The security test on master are failed to run.  Do you have any idea?

**Comment by bnevis-i** [comment]
Initial triage suggests that kong-migrations is failing to start due to kong-db (postgres) failing to start.

**Comment by bnevis-i** [comment]
Apparently the upstream postgres release was changed 4 days ago from a WARNING that POSTGRES_PASSWORD is unspecified to an ERROR.

`https://hub.docker.com/layers/postgres/library/postgres/9.6/images/sha256-92cba31ae0ab4480e227d03b68cfc9406b6c69d0b731f0b20e12de00c3d4c311?context=explore`

(Old prior to 9.6.17)
```
****************************************************
WARNING: No password has been set for the database.
         This will allow anyone with access to the
         Postgres port to access your database. In
         Docker's default configuration, this is
         effectively any other container on the same
         system.

         Use "-e POSTGRES_PASSWORD=password" to set
         it in "docker run".
****************************************************
```

(New: 9.6.17 or later)
```
Error: Database is uninitialized and superuser password is not specified.
       You must specify POSTGRES_PASSWORD for the superuser. Use
       "-e POSTGRES_PASSWORD=password" to set it in "docker run".

       You may also use POSTGRES_HOST_AUTH_METHOD=trust to allow all connections
       without a password. This is *not* recommended. See PostgreSQL
       documentation about "trust":
       https://www.postgresql.org/docs/current/auth-trust.html
```

**Comment by bnevis-i** [comment]
Fix submitted.

cc: @mkbhanda @tingyuz

**Comment by bnevis-i** [comment]
Colin submitted an unmerged fix for this days ago

https://github.com/edgexfoundry/developer-scripts/pull/219

Pulling my PR and referring to Colin's instead.

**Comment by cloudxxx8** [comment]
is this related to https://github.com/edgexfoundry/go-mod-secrets/issues/49 ?

**Comment by bnevis-i** [comment]
@cloudxxx8  No.  go-mod-secrets 49 causes services to fail to get the mongodb password.  This one just causes kong to fail to start because the Postgres database doesn't come up.

**Comment by bnevis-i** [comment]
I believe this issue can be closed now.

**Comment by cloudxxx8** [comment]
@bnevis-i since the blackbox test is still blocked now, I will close this issue once we can verify it on Jenkins

**Comment by bnevis-i** [comment]
@cloudxxx8 Is this still an issue?

**Comment by cloudxxx8** [comment]
yes, let's close this issue.
thanks for the reminder.
