### ISSUE TITLE
Need logging test to test logging service APIs

### ISSUE THREAD

**Issue by jinlinGuan** [edgexfoundry/blackbox-testing#391]
@andresrinivasan although we run logging with file as persistence, we still need to run logging test to make sure the API works.
Theoretically, logging service APIs can work with file

_Originally posted by @cloudxxx8 in https://github.com/edgexfoundry/blackbox-testing/pull/385_

**Comment by andresrinivasan** [comment]
Logging tests do not pass when logging to a file. I was thinking that when running the tests with Mongo, separately invoke the logging tests.

**Comment by cloudxxx8** [comment]
I understand that, but the Logging API should still be tested.  We will see how many APIs could be supported with file persistence.  We will make a try and discuss how to handle them in this issue.

**Comment by jinlinGuan** [comment]
Close this issue because the logging service has been deprecated in Geneva release and will be removed in the Hanoi release.
