### ISSUE TITLE
Mongo-based security blackbox tests are failing due to missing redis

### ISSUE THREAD

**Issue by bnevis-i** [edgexfoundry/blackbox-testing#401]
https://jenkins.edgexfoundry.org/view/blackbox-testing/job/blackbox-testing-security-centos7-blackbox-4c-2g-master/481/consoleText

```
------- scheduler ------
level=INFO ts=2020-02-27T12:35:40.079082701Z app=edgex-support-scheduler source=bootstrap.go:133 msg="Loaded configuration from http://edgex-core-consul:8500"
level=INFO ts=2020-02-27T12:35:40.079206721Z app=edgex-support-scheduler source=registry.go:49 msg="Using Registry from http://edgex-core-consul:8500"
level=INFO ts=2020-02-27T12:35:40.081921534Z app=edgex-support-scheduler source=config.go:138 msg="Writeable configuration has been updated from the Configuration Provider"
level=INFO ts=2020-02-27T12:35:40.170914438Z app=edgex-support-scheduler source=database.go:144 msg="Database connected"
level=INFO ts=2020-02-27T12:35:40.171794573Z app=edgex-support-scheduler source=loader.go:38 msg="loading intervals, interval actions ..."
level=ERROR ts=2020-02-27T12:35:40.186210316Z app=edgex-support-scheduler source=init.go:63 msg="Failed to load schedules and events Could not dial Redis: dial tcp: lookup edgex-redis on 127.0.0.11:53: no such host"
level=INFO ts=2020-02-27T12:35:40.186310411Z app=edgex-support-scheduler source=client.go:98 msg="context cancelled, dismiss the token renewal process"
level=INFO ts=2020-02-27T12:35:40.186327339Z app=edgex-support-scheduler source=database.go:158 msg="Database disconnected"
level=INFO ts=2020-02-27T12:35:40.186962752Z app=edgex-support-scheduler source=bootstrap.go:160 msg="Un-Registering service from the Registry"
```

This regression appears to be caused by the following PR:
https://github.com/edgexfoundry/edgex-go/commit/85e5bf6adee0c00ba03e0958022f91895438b52d

**Comment by bnevis-i** [comment]
cc @andresrinivasan

**Comment by andresrinivasan** [comment]
Apologies. Thought I had decoupled this. Will follow-up.

**Comment by cloudxxx8** [comment]
We opened a corresponding issue on developer-scripts
https://github.com/edgexfoundry/developer-scripts/issues/228

**Comment by andresrinivasan** [comment]
The code suggests this was resolved with PR #395. Looks like there's a disconnect between a couple of the scripts. And the coupling between the scripts is nasty. Might need some help.

**Comment by bnevis-i** [comment]
We will see.  In the above mentioned PR, `cmd/core-command/res/docker/configuration.toml` hard-codes the Redis host and the Redis database type.  There doesn't appear to be an obvious way to override.

**Comment by andresrinivasan** [comment]
Alright. Then we're a little hosed as I was so focused on the scripts I didn't even think about the TOML files. We should have a call to figure out a path forward.

**Comment by bnevis-i** [comment]
cc @tingyuz 

As all the other TOML files have already been converted, it seems the logical course of action would be go to all-in with security-enabled Redis.

Perhaps there is a way for blackbox testing to run a special container inject configuration into Consul to switch to mongodb, overriding the static TOML definition.

**Comment by bnevis-i** [comment]
@andresrinivasan,

@lenny-intel Suggests that you can set the following environment variable (Databases_Primary_Type) to specific sections on TOML, for example:

```Databases_Primary_Type: redisdb```

**Comment by cloudxxx8** [comment]
@bnevis-i we made some investigation today, and notice the environment variable override has been implemented in go-mod-bootstrap.  We also looked into the code, and didn't see the general environment variable override logic.
https://github.com/edgexfoundry/go-mod-bootstrap/blob/master/bootstrap/bootstrap.go#L114-L148
https://github.com/edgexfoundry/go-mod-bootstrap/blob/master/bootstrap/config/environment.go

@lenny-intel could you please help confirm my statement is correct?  If yes, may we open a PR in go-mod-bootstrap to add the environment variable override works for the database related configuration?

**Comment by lenny-goodell** [comment]
@cloudxxx8 , go-mod-bootstrap doesn't contain the environment override code, yet. Currently that code resides in config seed here:
https://github.com/edgexfoundry/edgex-go/blob/master/internal/seed/config/environment.go#L56
This is why the override must be in the global section or placed on config-seed  in the compose file.

**Comment by cloudxxx8** [comment]
Thanks, @lenny-intel 
This issue can be fixed by
https://github.com/edgexfoundry/developer-scripts/pull/232

**Comment by bnevis-i** [comment]
> This is why the override must be in the global section or placed on config-seed in the compose file.

Make that "This is why the override must be in the global section AND REFERENCED by config-seed in the compose file or specified in config-seed environment block directly".  Added similar advice to PR.

**Comment by bnevis-i** [comment]
Closing this ticket.  Blackbox test are healthy and passing with 1289 passes and 1 failures.
