### ISSUE TITLE
Add test for validity of new Reading "data type" properties

### ISSUE THREAD

**Issue by tsconn23** [edgexfoundry/blackbox-testing#408]
New properties to indicate the data type of a Reading.value have been added with the following PR

https://github.com/edgexfoundry/go-mod-core-contracts/pull/223

Please add a test to ensure the proper validity checks are running and a `400` status code is returned from the API in the case of invalid population.

**Comment by cloudxxx8** [comment]
@tsconn23 do you mind we move this issue to edgex-taf?  @weichou1229 and @cherrycl will take care of it.

**Comment by jdharms** [comment]
This makes sense to me-- @tsconn23 ?

**Comment by tsconn23** [comment]
@cloudxxx8 @jdharms No, I don't think that's a good idea. The reason is that in several QA/Test working group sessions recently, we've said blackbox tests should be kept up to date w/r/t the V1 API functionality and that TAF would initially target the V2 API endpoints. I am not aware of a change in this plan, and I think having a clean separation between how we test V1 and V2 makes sense.

**Comment by cloudxxx8** [comment]
no problem
