### ISSUE TITLE
Add test for persistence of new Reading data type properties

### ISSUE THREAD

**Issue by tsconn23** [edgexfoundry/blackbox-testing#409]
Given the new Reading properties indicating the data type of a `Reading.value`, provide or extend a blackbox test to save and retrieve these new values from the database. We need to ensure they're being stored and retrieved correctly. Persistence of these values was done in the following PR

https://github.com/edgexfoundry/edgex-go/pull/2428

**Comment by cloudxxx8** [comment]
@tsconn23 do you mind we move this issue to edgex-taf?  @weichou1229 and @cherrycl will take care of it.

**Comment by tsconn23** [comment]
@cloudxxx8 @jdharms No, I don't think that's a good idea. The reason is that in several QA/Test working group sessions recently, we've said blackbox tests should be kept up to date w/r/t the V1 API functionality and that TAF would initially target the V2 API endpoints. I am not aware of a change in this plan, and I think having a clean separation between how we test V1 and V2 makes sense.

**Comment by cloudxxx8** [comment]
no problem
