### ISSUE TITLE
[Fuji] Skip running test on Jenkins DATABASE=redis axis

### ISSUE THREAD

**Issue by jinlinGuan** [edgexfoundry/blackbox-testing#417]
Because integration-test jenkins jobs has been changed to use Matrix project type in [edgexfoundry/ci-management#581](https://github.com/edgexfoundry/ci-management/pull/581), the jobs for fuji branch is running test twice with Mongo DB. The DATABASE=redis axis should skip the test and make a build as successful.

**Comment by cloudxxx8** [comment]
closed by #418
