### ISSUE TITLE
GET device by name returning wrong Content-Type

### ISSUE THREAD

**Issue by jinlinGuan** [edgexfoundry/blackbox-testing#434]
The Content-Type should be `application/json`, but got `text/plain`.
```
13:01:47 ↳ http://localhost:48082/api/v1/device/name/:name
13:01:47   GET http://edgex-core-command:48082/api/v1/device/name/Livingroom automation [200 OK, 773B, 37ms]
13:01:47   ┌
13:01:47   │ 'Validation failed: ', null
13:01:47   └
13:01:47   ✓  Status code is 200
13:01:47   ✓  Response time is less than 1200 ms
13:01:47   ✓  Has Content-Type
13:01:47   4. Content-Type is application/json
13:01:47   ✓  Is Valid Response Schema
```

**Comment by akramtexas** [comment]
@jinlinGuan Making a note of your observation (above), and will investigate very shortly 👍

**Comment by akramtexas** [comment]
> @jinlinGuan Making a note of your observation (above), and will investigate very shortly 👍

@jinlinGuan Good catch. I have created a fix for this issue and requested @AnthonyMBonafide to review that `PR`: https://github.com/edgexfoundry/edgex-go/pull/2506 ✅

**Comment by akramtexas** [comment]
@jinlinGuan The `PR` that I refer to above has been approved and merged into `master`. I'll leave this issue open for you to please confirm and close out, thanks.

**Comment by jinlinGuan** [comment]
Verified on Jenkins test.
Closing this issue.

**Comment by akramtexas** [comment]
> Verified on Jenkins test.
> Closing this issue.

@jinlinGuan Thank you for your prompt follow-up 👍
