### ISSUE TITLE
Remove dependency on "volume" service

### ISSUE THREAD

**Issue by bnevis-i** [edgexfoundry/blackbox-testing#438]
Volume service has been rendered obsolete in the developer-scripts repo.

See draft PR https://github.com/edgexfoundry/developer-scripts/pull/258

Unfortuantely, there are several references to the volume service that need to be cleaned up in blackbox testing before volume service can be fully removed.

cc @cloudxxx8

**Comment by cloudxxx8** [comment]
volume service is the workaround to share volume for the old Docker version we made 4 years ago.  it's time to remove it.  thanks, @bnevis-i , for starting this work
