### ISSUE TITLE
Blackbox tests are failing on california branch for both x86 and arm servers.

### ISSUE THREAD

**Issue by JPWKU** [edgexfoundry/blackbox-testing#55]
https://jenkins.edgexfoundry.org/view/blackbox-testing/job/blackbox-testing-centos7-blackbox-4c-2g-california/45/
and 
https://jenkins.edgexfoundry.org/view/blackbox-testing/job/blackbox-testing-cavium-arm64-california/51/consoleText
@tsconn23 has some initial thoughts on the origins of the failure.  Specifically the use of `mongoimport`
```
[INFO] Init postman test data .
Info: Initiating EdgeX Test
tee: ./postman-test/scriptLogs/edgex31-07-2018_150014.log: No such file or directory
/bin/bash: mongoimport: command not found
Info: /etc/newman/DataDumps/coredata/eventDb.json data imported
/bin/bash: mongoimport: command not found
Info: /etc/newman/DataDumps/coredata/readingDb.json data imported
/bin/bash: mongoimport: command not found
Info: /etc/newman/DataDumps/coredata/valueDescriptorDb.json data imported
Info: Initiating Coredata Test.```

**Comment by weichou1229** [comment]
@JPWKU I'm working on this issue.
> tee: ./postman-test/scriptLogs/edgex31-07-2018_150014.log: No such file or directory  

This error can be solved by create a scriptLogs folder.

> /bin/bash: mongoimport: command not found

We found mongoimport is work fine on centos7, but it's fail on arm64 environment. So we will survey the problem with the image docker-edgex-mongo-arm64:0.6.0

**Comment by cloudxxx8** [comment]
Basically, the MongoDB version and installation way are different between docker-edgex-mongo-arm64:0.6.0 and docker-edgex-mongo:0.6.0, and we will see how to make mongoimport work in docker-edgex-mongo-arm64

**Comment by weichou1229** [comment]
@JPWKU @tsconn23 
1. This PR https://github.com/edgexfoundry/blackbox-testing/pull/59 is used to fix below error:
> tee: ./postman-test/scriptLogs/edgex31-07-2018_150014.log: No such file or directory

2. And We can add   
`mv mongodb-linux-aarch64-ubuntu1604-3.4.7/bin/mongoimport /usr/local/bin && \` in  
 https://github.com/edgexfoundry/docker-edgex-mongo/blob/master/Dockerfile.aarch64  
to fix below error:
>   /bin/bash: mongoimport: command not found

I created a branch https://github.com/weichou1229/docker-edgex-mongo/blob/add-mongoimport/Dockerfile.aarch64#L35 to test, and it's work fine.

3. Now docker-edgex-mongo-arm64:0.6.0 **mongodb version is 3.4.7** and docker-edgex-mongo:0.6.0 **mongodb version is 3.4.9**.  Is it need consistent?
I also build mongo-arm64 with 3.4.9, and it's work too.

**Comment by cloudxxx8** [comment]
issue fixed by https://github.com/IOTechSystems/postman-integration-test/pull/22

**Comment by cloudxxx8** [comment]
@JPWKU 
please help review the PR https://github.com/edgexfoundry/blackbox-testing/pull/59

**Comment by cloudxxx8** [comment]
https://github.com/edgexfoundry/blackbox-testing/pull/59 merged, closing this issue
