### ISSUE TITLE
Error: Newman >= v4 does not support the v1 collection

### ISSUE THREAD

**Issue by tsconn23** [edgexfoundry/blackbox-testing#61]
When reviewing the daily blackbox tests job, I noticed the job is failing due to the following error message repeated over and over in the logs.

```
Starting blackbox-testing_volume_1 ... [32mdone[0m
[1BPulling postman (postman/newman_ubuntu1404:)...
latest: Pulling from postman/newman_ubuntu1404
Digest: sha256:a94def5e27e103a1e13cc3b18c8d5a47e83af4f2bdd0ec1adb7a4e69409dd613
Status: Downloaded newer image for postman/newman_ubuntu1404:latest

  error: Newman >= v4 does not support the v1 collection format

  Use the Postman Native app to export collections in the v2 format
```
Example log here:
https://logs.edgexfoundry.org/production/vex-yul-edgex-jenkins-1/blackbox-testing-centos7-blackbox-4c-2g-california/51/console.log.gz

Example build here:
https://jenkins.edgexfoundry.org/view/blackbox-testing/job/blackbox-testing-centos7-blackbox-4c-2g-california/51/

**Comment by JPWKU** [comment]
We are pulling the https://hub.docker.com/r/postman/newman_ubuntu1404/tags/ latest tag, which was updated 5 hours ago.  Looks like it introduced a breaking change.  Will need the QA/Test team to pin to the appropriate version/docker tag here.

**Comment by weichou1229** [comment]
@JPWKU @tsconn23 
Yes, Newman 4.0.0 dropped support for the v1 Postman Collection format.
The reference link: https://github.com/postmanlabs/newman/blob/v4.0.0/CHANGELOG.yaml#L10.
Then I use 3.10.0 for test, it's work fine, so we can use **3.10.0** as appropriate version.
And I create a PR https://github.com/edgexfoundry/blackbox-testing/pull/62, please help review.

**Comment by tsconn23** [comment]
@weichou1229 Unfortunately this solution breaks ARM64. There are two environment shell scripts which set the appropriate image in the CI pipeline. The reference to the appropriate image needs to be set there. I am going to create separate issues.
