### ISSUE TITLE
Set Newman Image Version via Shell Scripts (master)

### ISSUE THREAD

**Issue by tsconn23** [edgexfoundry/blackbox-testing#63]
Instead of setting docker images to use when running blackbox tests inline within the docker-compose file, these need to be provided from environment shell scripts that reference the appropriate image for a given architecture when run through the CI pipeline. Currently the postman image is set inline in the docker-compose file. It works for non-ARM CI, but breaks in ARM.

**Comment by cloudxxx8** [comment]
fixed by #67
