### ISSUE TITLE
Set Newman Image v3.10.0 for ARM CI (california)

### ISSUE THREAD

**Issue by tsconn23** [edgexfoundry/blackbox-testing#65]
To be consistent, the current Newman ARM image used for blackbox tests needs to be version 3.10.0. Currently in Nexus, we have `nexus3.edgexfoundry.org:10004/postman-newman-arm64:3.9.4`

A new ARM image needs to be built based on 3.10.0

**Comment by lranjbar** [comment]
Closed because we need to update postman newman for Fuji

See #329
