### ISSUE TITLE
Remove Content-Type checking from Put AdminState and OperatingState API in core-command blackbox test

### ISSUE THREAD

**Issue by weichou1229** [edgexfoundry/blackbox-testing#74]
According to https://github.com/edgexfoundry/edgex-go/blob/master/api/raml/core-command.raml ,
* /device/{id}/opstate/{opState}
* /device/name/{name}/opstate/{opState}
* /device/{id}/adminstate/{adminState}
* /device/name/{name}/adminstate/{adminState}
These four apis no need check response content-type

**Comment by cloudxxx8** [comment]
fixed by https://github.com/edgexfoundry/blackbox-testing/pull/75
