### ISSUE TITLE
Update docker-compose to Version 3

### ISSUE THREAD

**Issue by tsconn23** [edgexfoundry/blackbox-testing#76]
Both @JPWKU and I strongly recommend updating the blackbox test docker-compose file to version 3 from version 2. The rationale is two-fold:

1.) The California 0.6.1 release docker-compose uses version 3 as will releases going forward
2.) The new ARM builders we are provisioning will be running recent versions of docker CE and docker-compose. We would like to avoid some of the incompatibility issues we've had in the past that required manual action during the release.

**Comment by cloudxxx8** [comment]
@weichou1229 @cherrycl
Get Bruce and Cherry aware

**Comment by tsconn23** [comment]
@weichou1229 @cherrycl @cloudxxx8 There was a PR https://github.com/edgexfoundry/blackbox-testing/pull/77 that was created for this and then closed without review or merge. What was the reason?

**Comment by weichou1229** [comment]
PR #77 still have some error and cherry have vacation in these days. So I will check PR and create new one.

**Comment by cloudxxx8** [comment]
fixed by #80
