### ISSUE TITLE
support-logging -- Max limit exceeded test verbiage check

### ISSUE THREAD

**Issue by tsconn23** [edgexfoundry/blackbox-testing#78]
The following test needs to have the verbiage in its "Response body is correct" check changed.

https://github.com/edgexfoundry/blackbox-testing/blob/5daed92bb4b5a8da6f317164850f47b7ed9a2e72/bin/postman-test/collections/support-logging.postman_collection.json#L1732

The verbiage has been changed in the following EdgeX-Go PR
https://github.com/edgexfoundry/edgex-go/pull/604

Rather than "Payload too large", it should instead look for "than configured limit".

**Comment by cloudxxx8** [comment]
@tsconn23 I thought we should not check the error message content, because it is the part easy to change and it is not specified in API.  Do you mind we just remove the body check?  Thanks.
@weichou1229 please follow this issue

**Comment by tsconn23** [comment]
I'm going to close this issue and drop the associated PR #79 based on some discussion in edgex-go PR https://github.com/edgexfoundry/edgex-go/pull/604.
