### ISSUE TITLE
RAML changes not accounted for in tests (core-data)

### ISSUE THREAD

**Issue by tsconn23** [edgexfoundry/blackbox-testing#86]
I have just rebased from master and re-imported the core-data collection for running Postman tests. It appears the changes we've made to the service endpoint return codes as specified in the RAML for the Delhi release have not been accounted for in the tests. We need to do this for all services prior to the Delhi release. In the screenshot below, all 503s were replaced with 500s but the tests are still expecting 503s.
<img width="556" alt="screen shot 2018-10-09 at 9 40 32 am" src="https://user-images.githubusercontent.com/1342980/46677086-82d87180-cba7-11e8-8581-250c18f2bb82.png">

**Comment by cloudxxx8** [comment]
fixed by https://github.com/edgexfoundry/blackbox-testing/pull/90

**Comment by cloudxxx8** [comment]
removed some inappropriate tests
