### ISSUE TITLE
Update versions to 1.0.0 in environment scripts -- master branch

### ISSUE THREAD

**Issue by tsconn23** [edgexfoundry/blackbox-testing#91]
- arm64_env.sh
- env.sh

Images pointed to 0.7.0 need to be pointed to 1.0.0

Also the scheduler image name needs to be corrected:
- arm64_env = docker-support-scheduler-go-arm64
- env = docker-support-scheduler-go

This needs to be done soon as the PR to update edgex-go has been created.

**Comment by cloudxxx8** [comment]
@FelixTing please take care of this issue

**Comment by FelixTing** [comment]
1.0.0 images hasn't been ready

![image](https://user-images.githubusercontent.com/43240457/47781340-6bb91980-dd38-11e8-854f-2dec1d0d1a00.png)

**Comment by tsconn23** [comment]
PR to rev edgex-go to 1.0.0 was merged today. Images have been pushed to nexus staging
https://nexus3.edgexfoundry.org/#browse/browse:docker.staging:v2%2Fdocker-core-data-go%2Ftags%2F1.0.0

**Comment by cloudxxx8** [comment]
@tsconn23 will we have v1.0 for current support-rulesengine?  if not, we don't need to change its version to v1.0.
