### ISSUE TITLE
Correct scheduler image name in environment scripts -- delhi branch

### ISSUE THREAD

**Issue by tsconn23** [edgexfoundry/blackbox-testing#92]
In the Delhi branch, the scheduler image name needs to be corrected:

arm64_env.sh = docker-support-scheduler-go-arm64
env.sh = docker-support-scheduler-go

Both are currently missing the "go"

**Comment by cloudxxx8** [comment]
@FelixTing please take care of this issue

**Comment by cloudxxx8** [comment]
fixed by #93
