### ISSUE TITLE
Some scripts in core-medata testing are empty

### ISSUE THREAD

**Issue by FelixTing** [edgexfoundry/blackbox-testing#98]
_core-metadata_
![image](https://user-images.githubusercontent.com/43240457/48175120-ada01c00-e345-11e8-9552-94c9b7599124.png)
![image](https://user-images.githubusercontent.com/43240457/48175123-b7298400-e345-11e8-9ac8-538a8126871a.png)
![image](https://user-images.githubusercontent.com/43240457/48175124-b98bde00-e345-11e8-8e17-0dcb10780d12.png)
![image](https://user-images.githubusercontent.com/43240457/48175126-bbee3800-e345-11e8-90da-66acd13bf136.png)
![image](https://user-images.githubusercontent.com/43240457/48175146-cb6d8100-e345-11e8-9cc4-8a3ee71ce38f.png)

**Comment by cloudxxx8** [comment]
@cherrycl please add those test when you have time in March

**Comment by cloudxxx8** [comment]
Since those tests are related to Device Report, and it will be removed in the future.
Thus, we won't fix this issue.
